name: 'Publish Assets'
description: 'Publishes assets to a GitHub release'
inputs:
  release_tag:
    description: 'The tag of the release to use'
    default: 'latest'
  asset_dir:
    description: 'The dir containing all assets to publish to the GitHub release'
    required: true
outputs:
  download_urls:
    description: 'The URLs to download the assets from'
runs:
  using: 'node20'
  main: 'dist/index.js'