name: Release

on:
  push:
    branches:
      - main

env:
  node-js-version: 18.x
  author-name: Marc Scheib
  author-email: marc.scheib@cycrilabs.com

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout [${{ github.head_ref || github.ref_name }}]
        uses: actions/checkout@v4

      - name: Setup Node.js [${{ env.node-js-version }}]
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node-js-version }}

      - name: Install Dependencies
        run: npm i --prefer-offline --no-audit --force

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_AUTHOR_NAME: ${{ env.author-name }}
          GIT_AUTHOR_EMAIL: ${{ env.author-email }}
        run: npx semantic-release
